### ISSUE TITLE
could not run

### ISSUE THREAD

**Issue by odarcan** [seroteunine/Spotifast#2]
I installed selenium with pip install selenium
but how do you install webdriver?

I get error

**_python3 main.py** 
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.12) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "main.py", line 5, in <module>
    from webdriver_manager.chrome import ChromeDriverManager
ModuleNotFoundError: No module named 'webdriver_manager'_

**Comment by seroteunine** [comment]
You are missing some modules. Either install with 'pip install webdriver-manager' or even better; download requirements.txt from this repo and use 'pip install -r /path/to/requirements.txt' Requirements.txt file contains all the modules you need in one file.

**Comment by seroteunine** [comment]
Please let me know if it works

**Comment by odarcan** [comment]
I dont use python almost at all
I didnt know webdriver was called webdriver-manager,
also I didnt know requirements.txt was a install list or that it is even used with pip, maybe add that to instructions

It did install stuff but stumbled over "testresources" when installing, I wrote pip install testresources  manually

then it gave error 

ain.py:19: DeprecationWarning: executable_path has been deprecated, please pass in a Service object
  browser = webdriver.Chrome(ChromeDriverManager().install())
Traceback (most recent call last):
  File "main.py", line 19, in <module>
    browser = webdriver.Chrome(ChromeDriverManager().install())
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/chrome/webdriver.py", line 69, in __init__
    super().__init__(DesiredCapabilities.CHROME['browserName'], "goog",
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/chromium/webdriver.py", line 92, in __init__
    super().__init__(
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 270, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 363, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/remote/webdriver.py", line 428, in execute
    self.error_handler.check_response(response)
  File "/home/myname/.local/lib/python3.8/site-packages/selenium/webdriver/remote/errorhandler.py", line 243, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot find Chrome binary
Stacktrace:
#0 0x555e103cb693 <unknown>
#1 0x555e101c4b0a <unknown>
#2 0x555e101e746e <unknown>
#3 0x555e101e51f4 <unknown>
#4 0x555e10220953 <unknown>
.
.
.
.

**Comment by odarcan** [comment]
I installed chromium on my linux mint

now it says

This version of ChromeDriver only supports Chrome version 105 
Current browser version is 104.0.5112.101 with binary path /usr/bin/chromium

at the end

**Comment by seroteunine** [comment]
Please just install with requirements.txt otherwise i cant help you

**Comment by seroteunine** [comment]
im closing this issue, if you have any problems, message me

**Comment by odarcan** [comment]
Hello sorry for late response

I would really like to get this going

It is a feature I have not been able to get for spotify, I am oldschool and still use mp3

thanks!

**Comment by seroteunine** [comment]
okay. but please just follow the instructions then;
-download python3 on your machine. ( https://realpython.com/installing-python/ )
-download or clone this github reposity ( https://docs.github.com/en/repositories/creating-and-managing-repositories/cloning-a-repository ) 
-switch to this downloaded folder on your commandline (cd command)
-run $ pip install -r requirements.txt
-change the spotify credentials in the main.py script file
-run the script with $ python main.py
